name: GitHub Actions Demo Terraform lint
run-name: Terraform Lint
on:
  push:
    paths:
      - 'terraform/**'
jobs:
  Terraform_Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Lint Terraform
        uses: actionshub/terraform-lint@main
        with:
          path: terraform/infra